### ISSUE TITLE
Error in get_collectri() from OmnipathR: Argument length zero and partial match warning

### ISSUE THREAD

**Issue by ranxm2** [saezlab/decoupleR#139]
I am encountering an issue when trying to use the get_collectri() function from the OmnipathR package to retrieve the CollecTRI network. The function is throwing errors and warnings, and it appears that there is a problem with the way arguments are being handled.

```
# Code to reproduce the issue
library(OmnipathR)

# Attempt to retrieve the CollecTRI network for humans
net <- get_collectri(organism = "human", split_complexes = FALSE)

[2024-10-03 11:23:38] [WARN]    [OmnipathR] Accessing `collectri` as a static table: this is not the recommended way to access OmniPath data; it is only a backup plan for situations when our server or your computer is experiencing issues.
Error in if (.keep) . else select(., -!!evs_col) : 
  argument is of length zero
In addition: Warning message:
In (function (query_type, organism = 9606, resources = NULL, datasets = NULL,  : 
  partial argument match of 'genesymbol' to 'genesymbols'


```
Additional Details:

I am using R version [4.4.1] and OmnipathR version [3.12.3 version].
The error seems related to the select(., -!!evs_col) operation, suggesting that a required column might be missing or empty.
There is also a warning about a partial argument match between genesymbol and genesymbols.

**Comment by deeenes** [comment]
Hello @ranxm2,

Here we see two independent issues: 1) The warning is due to the name conflict between the `genesymbol_resource` and `genesymbols` arguments in R's partial matching; this has been fixed in more recent versions of `OmnipathR`. 2) The missing `evidences` column is a consequence of a download failure, unfortunately the original error message is hidden (probably in the log), and it might have several reasons. [This one](https://github.com/saezlab/OmnipathR/issues/106) is a likely reason, and it's been fixed already.

Overall, I recommend updating `OmnipathR` directly from GitHub: 

```
library(OmnipathR)
omnipath_wipe_cache()

library(remotes)
remotes::install_github('saezlab/OmnipathR')
```

Then in a new session:

```
library(decoupleR)
library(OmnipathR)

net <- get_collectri(organism = "human", split_complexes = FALSE)

# if error happens again, please share the log:
omnipath_log()
```

**Comment by ranxm2** [comment]
Hi @deeenes,

I use the python to download the net successfully. 

```
import scanpy as sc
import decoupler as dc
import pandas as pd

net = dc.get_collectri(organism='human', split_complexes=False)
net

# save the network as df
net.to_csv('reference/collectri_human.csv', index=True)

```
Thank you for your help. But the code you provide seems still not working.

Here is the code
```

> library(OmnipathR)
Warning message:
package ‘OmnipathR’ was built under R version 4.4.1 
> omnipath_wipe_cache()
Error in omnipath_wipe_cache() : 
  could not find function "omnipath_wipe_cache"


```
